# Lab-1-NumPy Exercises 



#### Import NumPy 

In [4]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 6 twelves

In [7]:
np.ones(12)*6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

#### Create an array of the integers from 50 to 75

In [8]:
np.arange(50,76)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75])

#### Create an array of all the odd integers from 50 to 75

In [9]:
arr = np.arange(50,76)
arr5 = arr[arr % 2 == 1]
arr5

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75])

#### Create a 3x4 matrix with values ranging from 0 to 12

In [10]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Create a 5x5 identity matrix

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand(1)

array([0.01356842])

# Use NumPy to generate an array of 10 random numbers sampled from a standard normal distribution

In [13]:
np.random.randn(10)

array([-1.8471753 , -1.90914427, -1.56975119,  1.3477759 ,  0.16378378,
        1.25547739, -1.12249596, -1.59469178, -0.0247459 , -0.45884627])

#### Create the following matrix:

In [14]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Create the following matrix:

In [15]:
np.arange(10,1010,10).reshape(10,10)

array([[  10,   20,   30,   40,   50,   60,   70,   80,   90,  100],
       [ 110,  120,  130,  140,  150,  160,  170,  180,  190,  200],
       [ 210,  220,  230,  240,  250,  260,  270,  280,  290,  300],
       [ 310,  320,  330,  340,  350,  360,  370,  380,  390,  400],
       [ 410,  420,  430,  440,  450,  460,  470,  480,  490,  500],
       [ 510,  520,  530,  540,  550,  560,  570,  580,  590,  600],
       [ 610,  620,  630,  640,  650,  660,  670,  680,  690,  700],
       [ 710,  720,  730,  740,  750,  760,  770,  780,  790,  800],
       [ 810,  820,  830,  840,  850,  860,  870,  880,  890,  900],
       [ 910,  920,  930,  940,  950,  960,  970,  980,  990, 1000]])

# Create an array of 25 linearly spaced points between 0 and 1:

In [16]:
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

## Numpy Indexing and Selection

You are given the below matrix and find the resultant matrix by answering the questions

In [17]:
arr2 = np.arange(51,76).reshape(5,5)
arr2

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75]])

In [18]:
arr2[2 : , 1 :]

array([[62, 63, 64, 65],
       [67, 68, 69, 70],
       [72, 73, 74, 75]])

In [19]:
arr2[3,4]

70

In [20]:
arr2[:3,1].reshape(3,1)

array([[52],
       [57],
       [62]])

In [21]:
arr2[4,:]

array([71, 72, 73, 74, 75])

In [22]:
arr2[3: , :]

array([[66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75]])

### Perform the following operations

#### Get the sum of all the values in the  matrix

In [23]:
np.sum(arr2)

1575

#### Get the standard deviation of the values in matrix

In [24]:
np.std(arr2)

7.211102550927978

#### Get the sum of all the columns in matrix

In [25]:
l = []
for i in range(5):
  s = np.sum(arr2[ : , i ])
  l.append(s)
arr = np.array(l)
arr

array([305, 310, 315, 320, 325])

#### Get the sum of all the rows in matrix

In [26]:
l1 = []
for i in range(5):
  s = np.sum(arr2[ i , : ])
  l1.append(s)
arr3 = np.array(l1)
arr3

array([265, 290, 315, 340, 365])